services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - node_modules:/app/node_modules
      - .:/app  # Pour s'assurer que le script wait-for-it.sh soit inclus

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: file_server
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  node_modules: